GET http://localhost:5213/

###
GET http:// localhost:5213/about/

###
GET http://localhost:5213/contact/info/

###
GET http://localhost:5213/testimonial/

###
POST http://localhost:5213/post/testimonial/

###
PUT http://localhost:5213/put/testimonial/


###
DELETE http://localhost:5213/delete/testimonial/